name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.get_version.outputs.version-without-v }}
          body: |
            Download from [Maven Central](https://search.maven.org/artifact/io.github.ititus/dds/${{ steps.get_version.outputs.version-without-v }}/jar).
          draft: false
          prerelease: false

      - name: Publish to Maven Central
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_ossrh_staging_profile_id: ${{ secrets.OSSRH_STAGING_PROFILE_ID }}
          ORG_GRADLE_PROJECT_ossrh_username: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signing_key: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signing_password: ${{ secrets.SIGNING_PASSWORD }}
